/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_log_analyzer_nativebridge_LogAnalyzerNative */

#ifndef _Included_com_example_log_analyzer_nativebridge_LogAnalyzerNative
#define _Included_com_example_log_analyzer_nativebridge_LogAnalyzerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_log_analyzer_nativebridge_LogAnalyzerNative
 * Method:    analyzeLog
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_log_1analyzer_nativebridge_LogAnalyzerNative_analyzeLog
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
